version: '3.9'
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=superSecretPassword
      - DB_NAME=pennRoguelikeDb
  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superSecretPassword
      POSTGRES_DB: pennRoguelikeDb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

