// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package model

import (
	"encoding/json"
)

type Level struct {
	ID  int32
	Map json.RawMessage
}

type Player struct {
	ID        int32
	Hitpoints int32
	StartX    int32
	StartY    int32
	CurrX     int32
	CurrY     int32
	LevelID   int32
}
