{
 "title": "Database",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average Execution Time [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(CreateLevelWithTx_sum[5m]) / rate(CreateLevelWithTx_count[5m])",
     "legendFormat": "CreateLevelWithTx"
    },
    {
     "expr": "rate(CreatePlayerWithTx_sum[5m]) / rate(CreatePlayerWithTx_count[5m])",
     "legendFormat": "CreatePlayerWithTx"
    },
    {
     "expr": "rate(GetFirst_sum[5m]) / rate(GetFirst_count[5m])",
     "legendFormat": "GetFirst"
    },
    {
     "expr": "rate(GetPlayerByLevelIDAndLockWithTx_sum[5m]) / rate(GetPlayerByLevelIDAndLockWithTx_count[5m])",
     "legendFormat": "GetPlayerByLevelIDAndLockWithTx"
    },
    {
     "expr": "rate(UpdatePlayer_sum[5m]) / rate(UpdatePlayer_count[5m])",
     "legendFormat": "UpdatePlayer"
    }
   ]
  },
  {
   "title": "Total Request Count [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(CreateLevelWithTx_count[5m])",
     "legendFormat": "CreateLevelWithTx"
    },
    {
     "expr": "increase(CreatePlayerWithTx_count[5m])",
     "legendFormat": "CreatePlayerWithTx"
    },
    { "expr": "increase(GetFirst_count[5m])", "legendFormat": "GetFirst" },
    {
     "expr": "increase(GetPlayerByLevelIDAndLockWithTx_count[5m])",
     "legendFormat": "GetPlayerByLevelIDAndLockWithTx"
    },
    {
     "expr": "increase(UpdatePlayer_count[5m])",
     "legendFormat": "UpdatePlayer"
    }
   ]
  },
  {
   "title": "Request Rate/Second [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(CreateLevelWithTx_count[5m])",
     "legendFormat": "CreateLevelWithTx"
    },
    {
     "expr": "rate(CreatePlayerWithTx_count[5m])",
     "legendFormat": "CreatePlayerWithTx"
    },
    { "expr": "rate(GetFirst_count[5m])", "legendFormat": "GetFirst" },
    {
     "expr": "rate(GetPlayerByLevelIDAndLockWithTx_count[5m])",
     "legendFormat": "GetPlayerByLevelIDAndLockWithTx"
    },
    { "expr": "rate(UpdatePlayer_count[5m])", "legendFormat": "UpdatePlayer" }
   ]
  }
 ]
}