{
 "title": "HTTP",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average Response Time (/level/submit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_response_duration_POST_:level:submit_sum[5m])\n/\nrate(http_response_duration_POST_:level:submit_count[5m])\n",
     "legendFormat": "/level/submit"
    }
   ]
  },
  {
   "title": "Average Response Time (/player/move)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_response_duration_POST_:player:move_sum[5m])\n/\nrate(http_response_duration_POST_:player:move_count[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate/Second Increase [5m] (/level/submit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_response_duration_POST_:level:submit_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate/Second Increase [5m] (/player/move)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_response_duration_POST_:player:move_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}